
%% AQuA2_CFU.m read metadata file from AQuA2 and CFU GUI. 
% For all events detected, it gives 15 values/features, including: Index number (=event number), in sequential order,
% area, circularity, max Dff, duration, etc, for all events. The new AQuA2 also outputs information about detected cells ("CFU") which 
% is provided as cfuInfo1/2, depending on the channel chosen. It gives the list of cells detected and their corresponding list of events.
% This detection has to be somewhat manual, in order to adjust overlap threshold (important!!!) and identify areas where detection is not clear

clear all;

% Load metadata files generated by AQuA
AQuA2_CFUinfo_dir = ['D:\2photon\Simone\Simone_Macrophages\Pf4Ai162-1\221109_FOV3\AQuA2\' ...
    'Pf4Ai162-1_221109_FOV3_run1_reg_max_z3-8_green_Substack (1-900)_AQuA_res_cfu'];
AQuA2_CFUinfo = load(AQuA2_CFUinfo_dir);
AQuA2_Feature_dir = ['D:\2photon\Simone\Simone_Macrophages\Pf4Ai162-1\221109_FOV3\AQuA2\Pf4Ai162-1_221109_FOV3_run1_reg_max_z3-8_green_Substack (1-900)\' ...
    'Pf4Ai162-1_221109_FOV3_run1_reg_max_z3-8_green_Substack (1-900)_AQuA2'];
AQuA2_Feature = load(AQuA2_Feature_dir);

% Set the output directory to save files
outputDir = fileparts(AQuA2_CFUinfo_dir);
cd(outputDir); %change directory of current folder

%% Create a table (finalResults) with final results of all cells and median of features
%Features to remove 
rowsIndicesToDelete = [1,2,3,7,15];

%Events to delete


%Get metadata results of ALL events
results = AQuA2_Feature.res.featureTable1;
expandedResults = cell2table(results.ftsTb); %expanded events without features column
expandedResults(rowsIndicesToDelete,:) = [];

%Create a finalResults table features
resultsFinal = results; %copy of metadata results table
resultsFinal.ftsTb = []; %assign empty values
resultsFinal(rowsIndicesToDelete,:) = []; %remove features

%% Results of CFU
% OPTION1 - Initialize variables and create a table
cellList = AQuA2_CFUinfo.cfuInfo1(:,1); % OR cell(size(cfuInfo1, 1), 1);
eventList = AQuA2_CFUinfo.cfuInfo1(:,2); % OR cell(size(cfuInfo1, 1), 1);
cellList_eventList = table(cellList, eventList);

%if there are merging CFUs


% Iterate through CFU cell array
for row = 1:size(AQuA2_CFUinfo.cfuInfo1, 1)

    % From one cell, extract its ID and its list of events - do for all cells
    cellID = AQuA2_CFUinfo.cfuInfo1{row, 1};
    cellEvents = AQuA2_CFUinfo.cfuInfo1{row, 2};
    
    % Initialize an array to store median values for a group of events
    EventFeatures = table2array(expandedResults(:,cellEvents));
    EventFeatures_median = array2table(median(EventFeatures,2),"VariableNames","cell " + row);
    
    % Populate resultFinal table with median of each cell, by feature, iterating cell in cellList
    resultsFinal = [resultsFinal, EventFeatures_median];
end

%% Save 
[filepath,name,ext] = fileparts(AQuA2_CFUinfo_dir);
fileTemp = extractBefore(name, "_AQuA_res_cfu");
save(strcat(fileTemp,"_analysis")); % save metadata
writetable(resultsFinal,strcat(fileTemp,"_resultsFinal"),"WriteRowNames",true,"FileType","spreadsheet"); %save resultsFinal


%% Combine results for each animal

