% Clear any previous variables in the Workspace and Command Window to start fresh
clear; clc; close all;

% Load res_cfu.mat file generated by AQuA
load('D:\2photon\Simone\Simone_Macrophages\Pf4Ai162-2\221130_FOV2\AQuA2\Pf4Ai162-2_221130_FOV2_run1_reg_Z01_green_Substack(1-900)_AQuA_res_cfu.mat')

% Create a nx3 cell array (column1=CFUID; column2=events associated; column3=Average dF curve of each CFU)
CFU_EventFluorescenceData = cfuInfo1;
columnIndicesToDelete = [3,4,5,7,8];
CFU_EventFluorescenceData(:,columnIndicesToDelete) = [];

% Create a nx2 cell array (column1=CFUID; column2=Average dF curve of each CFU)
CFU_FluorescenceData = cfuInfo1;
columnIndicesToDelete2 = [2,3,4,5,7,8];
CFU_FluorescenceData(:,columnIndicesToDelete2) = [];

%Export nx2 cell array to an excel spreadsheet (column1=CFUID; column2=Average dF curve of each CFU), adding ROW1=FRAMES
%CFU_FluorescenceDataNew = CFU_FluorescenceData(end+1,:); %add 1dt row which corresponds to  number of frames
writecell(CFU_FluorescenceData, 'Pf4Ai162-2_221130_FOV2_run1_reg_Z01_green_AQuA_res_cfu.xlsx')

cd('H:\Matlab_others\Matlab_toplot\AQuA2\')
data_filename = 'test_fluorescence_macrophages.xlsx';
data = readmatrix(data_filename, 'NumHeaderLines', 0); % don't read variable names

% Default Parameters
cmap = redbluecmap; %original color map contain just 11 colors
newCmap = imresize(cmap, [128, 3]); %increase number of colors
newCmap = min(max(newCmap, 0), 1);
colorLimits = [-1 3];
missingData = [.7 .7 .7];

%Create multiple heatmaps by cell
%subplot(3,1,1);
h1 = heatmap(data(2:5, 2:1801), ...
    'Colormap', newCmap, ...
    'GridVisible','off', ...
    'ColorLimits', colorLimits, ...
    'MissingDataColor', missingData, ...
    XDisplayLabels=string(data(1, 2:1801)), ...
    YDisplayLabels=string(data(2:5, 1)), ...
    FontSize=8); 
%xlabel("Time (min)"); 
%ylabel("Fiber ID");
%title("Ongoing Activity"); 
saveas(h1, 'Heatmap1_230516.pdf')




