clc;
clear 
close all;

cd('R:\Levy Lab\Simone\Matlab_toplot\')
data_filename = 'Last_ongoing_activity_230522_new_DL89.xlsx';
data = readmatrix(data_filename, 'NumHeaderLines', 0); % don't read variable names

% Default Parameters
cmap = redbluecmap; %original color map contain just 11 colors
newCmap = imresize(cmap, [128, 3]); %increase number of colors
newCmap = min(max(newCmap, 0), 1);
colorLimits = [-2 4];
missingData = [.7 .7 .7];

%Create multiple heatmaps by fiber
%subplot(3,1,1);
h1 = heatmap(data(2:5, 2:end), ...
    'Colormap', newCmap, ...
    'GridVisible','off', ...
    'ColorLimits', colorLimits, ...
    'MissingDataColor', missingData, ...
    XDisplayLabels=string(data(1, 2:end)), ...
    YDisplayLabels=string(data(2:5, 1)), ...
    FontSize=8); 
%xlabel("Time (min)"); 
%ylabel("Fiber ID");
%title("Ongoing Activity"); 
saveas(h1, 'Heatmap1_230516.pdf')

%subplot(3,1,2);
h2 = heatmap(data(7:12, 2:end), ...
    'Colormap', newCmap, ...
    'GridVisible','off', ...
    'ColorLimits', colorLimits, ...
    'MissingDataColor', missingData, ...
    XDisplayLabels=string(data(1, 2:end)), ...
    YDisplayLabels=string(data(7:12, 1)), ...
    FontSize=8);
%xlabel("Time (min)"); 
%ylabel("Fiber ID");
%title("Ongoing Activity"); 
saveas(h2, 'Heatmap2_230516.pdf')

%subplot(3,1,3);
h3 = heatmap(data(14:31, 2:end), ...
    'Colormap', newCmap, ...
    'GridVisible','off', ...
    'ColorLimits', colorLimits, ...
    'MissingDataColor', missingData, ...
    XDisplayLabels=string(data(1, 2:end)), ...
    YDisplayLabels=string(data(14:31, 1)), ...
    FontSize=8); 
%xlabel("Time (min)"); 
%ylabel("Fiber ID");
%title("Ongoing Activity"); 
saveas(h3, 'Heatmap3_230516.pdf');

% ax = gca;
% ax.Title = "Ongoing Activity";
% ax.FontSize = 10;
% ax.TickLength = [0.02 0.02];
% ax.Colormap = newCmap;
% ax.XDisplayLabels = data(1, 2:end);
% ha=get(gcf,'children');